### ISSUE TITLE
question about reloading configs

### ISSUE THREAD

**Issue by xzahalko** [blaxxun-boop/ConfigWatcher#2]
Sorry to bother, i just wanted to check that everything after Hildir's Request. 0.217.14 is ok.

We are preparing new server and I found out that after copying or updating a config file Vaheim crashed,
or looks like on dedicated server it corrupted the database.

I'am not sure about it. Just wanted top check it.

Thanks a lot

**Comment by draco1122** [comment]
Having same issue without Config watcher so wondering if a new vanilla bug. But, server crashes \ disconnects when editing configs.

**Comment by blaxxun-boop** [comment]
Config Watcher doesn't touch the Valheim code at all. It cannot break after a Valheim update.

And your issue sounds like you have a mod that adds its own filewatcher for configs, for whatever reason, and messed that up.

**Comment by xzahalko** [comment]
thanks for the reply
we have removed config watcher and we still have the problem with crashes
it is like you have written, problem is probably with the Valheim update and some mod,
but we have a clean log without errors

**Comment by xzahalko** [comment]
sorry for reporting a problem

**Comment by xzahalko** [comment]
It is realy strange. Just one player has a problem and when he logs into the game he coprupts a database.
We have done a clean instalation like at the others. He has created a new person for the game
and still he crashes the game. If you have any suggestions I would be realy gratfull.
Thanks
